[package]
name = "recern-vector"
description = "A single-file, embedded, inspectable vector database"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde_json.workspace = true
