"""Renders bench/results/*.json into bench/RESULTS.md."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TARGETS = [0.90, 0.95, 0.99]
ORDER = ["recern", "faiss-hnsw", "lancedb-hnsw", "lancedb-pq", "lancedb-pq-tuned", "sqlite-vec"]


def size(n):
    return f"{n / 2**20:,.0f} MB" if n < 2**30 else f"{n / 2**30:.2f} GB"


def seconds(s):
    return f"{s:,.0f} s" if s >= 10 else f"{s:.1f} s"


def build_cell(key, engine, scaling):
    """Build time with its thread count, preferring the parallel faiss build so
    the column compares like with like."""
    if key == "faiss-hnsw" and scaling:
        cores = scaling["cores"]
        return f"{seconds(scaling['seconds'][f'faiss_{cores}'])} ({cores})"
    threads = engine["threads"].split()[0]
    label = {"multi-threaded": "all", "1": "1"}.get(threads, threads)
    return f"{seconds(engine['build_s'])} ({label})"


def best_at(runs, target):
    """Fastest configuration reaching the target recall."""
    ok = [r for r in runs if r["recall"] >= target]
    return max(ok, key=lambda r: r["qps"]) if ok else None


def name(e):
    return f"{e['engine']} · {e['index']}"


def render(report):
    engines = [(key, report["engines"][key]) for key in ORDER if key in report["engines"]]
    m = report["machine"]
    lines = [
        f"## {report['dataset'].removesuffix('.hdf5')}",
        "",
        f"{report['records']:,} vectors × {report['dim']} dims, {report['metric']} · "
        f"{report['queries']:,} queries, top-{report['k']} · {m['cpu']}, {m['memory_gb']} GB, {m['os']}",
        "",
        "### Throughput at a recall target",
        "",
        "Single-query latency from Python (one query at a time). QPS is the fastest configuration reaching the target.",
        "",
        "| Engine | " + " | ".join(f"recall ≥ {t:.2f}" for t in TARGETS) + " | Build (threads) | On disk |",
        "|---|" + "---|" * (len(TARGETS) + 2),
    ]
    scaling = report.get("build_scaling")
    for key, e in engines:
        cells = []
        for t in TARGETS:
            r = best_at(e["runs"], t)
            cells.append(f"{r['qps']:,.0f} QPS · {r['p50_ms']:.2f} ms" if r else "—")
        lines.append(f"| {name(e)} | " + " | ".join(cells) + f" | {build_cell(key, e, scaling)} | {size(e['disk_bytes'])} |")

    if scaling:
        cores, s = scaling["cores"], scaling["seconds"]
        single = report["engines"].get("faiss-hnsw", {}).get("build_s")
        lines += [
            "",
            "### Index build time",
            "",
            f"HNSW m=16, ef_construction=200. Parallel builds use all {cores} cores. "
            "Build times vary by about 10–15% between runs on this laptop.",
            "",
            f"| Engine | 1 thread | {cores} threads | Speedup |",
            "|---|---|---|---|",
            f"| Recern Vector | {seconds(s['recern_1'])} | {seconds(s[f'recern_{cores}'])} | "
            f"{s['recern_1'] / s[f'recern_{cores}']:.1f}× |",
        ]
        if single:
            lines.append(
                f"| faiss HNSWFlat | {seconds(single)} | {seconds(s[f'faiss_{cores}'])} | "
                f"{single / s[f'faiss_{cores}']:.1f}× |"
            )

    lines += ["", "### Full sweep", "", "| Engine | Setting | Recall@10 | p50 ms | p95 ms | QPS |", "|---|---|---|---|---|---|"]
    for _, e in engines:
        for r in e["runs"]:
            lines.append(
                f"| {e['engine']} {e['index'].split()[0].rstrip(',')} | {r['config']} | {r['recall']:.4f} | "
                f"{r['p50_ms']:.3f} | {r['p95_ms']:.3f} | {r['qps']:,.0f} |"
            )
    notes = []
    for _, e in engines:
        extra = [f"threads: {e['threads']}"]
        if "save_s" in e:
            extra.append(f"save {e['save_s']:.1f} s, open {e['open_s']:.1f} s")
        if "queries" in e:
            extra.append(f"measured on the first {e['queries']} queries")
        notes.append(f"- {e['engine']} ({e['index'].split()[0].rstrip(',')}): " + "; ".join(extra))
    return "\n".join(lines + ["", *notes, ""])


def main():
    paths = [ROOT / "results" / f"{name}.json" for name in ("sift", "glove")]
    reports = [json.loads(p.read_text()) for p in paths if p.exists()]
    body = [
        "# ANN benchmark results",
        "",
        "Generated by `bench/report.py` from `bench/results/*.json`. Setup and reproduction: [bench/README.md](README.md).",
        "",
        "Every engine answers top-10 queries one at a time from Python; latency includes each library's Python overhead. "
        "Searches run on one thread for Recern Vector and faiss. Recern Vector builds on all cores, faiss on one "
        "(both are compared under *Index build time*); LanceDB builds and searches multi-threaded.",
        "",
        *[render(r) for r in reports],
    ]
    (ROOT / "RESULTS.md").write_text("\n".join(body))
    print((ROOT / "RESULTS.md").read_text())


if __name__ == "__main__":
    main()
